include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - references/**
    - '**/*.g.dart'
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
  errors:
    missing_required_param: error
    missing_return: error
    dead_code: warning

linter:
  rules:
    # Style
    prefer_single_quotes: true
    prefer_const_constructors: true
    prefer_const_declarations: true
    prefer_final_fields: true
    prefer_final_locals: true
    # Safety
    avoid_dynamic_calls: true
    avoid_print: true
    avoid_empty_else: true
    cancel_subscriptions: true
    close_sinks: true
    # Docs
    public_member_api_docs: false
